2021-04-15 13:05:31,657 - Logconfig.py - INFO - --------------------------test_TestLogin_01测试开始----------------------------------------
2021-04-15 13:05:34,789 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-04-15 13:05:34,924 - Logconfig.py - INFO - start monitor!
2021-04-15 13:05:43,066 - Logconfig.py - INFO - 以下为退出登录操作
2021-04-15 13:05:45,482 - Logconfig.py - INFO - stop monitor
2021-04-15 13:05:47,589 - Logconfig.py - INFO - -----------------------------------test_TestLogin_01测试结束-------------------------------
2021-04-22 09:22:49,054 - Logconfig.py - INFO - --------------------------test_TestDownload_02测试开始----------------------------------------
2021-04-22 09:22:52,120 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-04-22 09:22:52,139 - Logconfig.py - INFO - start monitor!
2021-04-22 09:23:02,142 - Logconfig.py - INFO - 新建文件夹:清空专用
2021-04-22 09:23:05,559 - Logconfig.py - INFO - 新建文件夹:清空专用
2021-04-22 09:23:08,776 - Logconfig.py - INFO - 删除所有文件
2021-04-22 09:23:17,312 - Logconfig.py - INFO - 新建文件夹:被下载的文件夹
2021-04-22 09:23:22,633 - Logconfig.py - INFO - 新建文件:ss,ss下载的文件,下载
2021-04-22 09:23:35,854 - Logconfig.py - INFO - 编辑文件: ss, 下载
2021-04-22 09:23:35,933 - Logconfig.py - INFO - 编辑地址：https://www.yozocloud.cn/third.html?fileId=1061595821576370&fileName=%25E6%2596%25B0%25E5%25BB%25BA%25E8%25A1%25A8%25E6%25A0%25BC%25E6%2596%2587%25E6%25A1%25A3.xlsx&version=-1&method=2&uuid=ym1619054604430
2021-04-22 09:23:49,039 - Logconfig.py - INFO - 新建文件:wp,wp下载的文件,下载
2021-04-22 09:24:00,566 - Logconfig.py - INFO - 编辑文件: wp, 下载
2021-04-22 09:24:00,659 - Logconfig.py - INFO - 编辑地址：https://www.yozocloud.cn/third.html?fileId=3099188305943981&fileName=%25E6%2596%25B0%25E5%25BB%25BA%25E6%2596%2587%25E5%25AD%2597%25E6%2596%2587%25E6%25A1%25A3.docx&version=-1&method=2&uuid=ym1619054629354
2021-04-22 09:24:15,261 - Logconfig.py - INFO - 新建文件:pg,pg下载的文件,下载
2021-04-22 09:24:30,316 - Logconfig.py - INFO - 编辑文件: pg, 下载
2021-04-22 09:24:30,402 - Logconfig.py - INFO - 编辑地址：https://www.yozocloud.cn/b/third.html?fileId=177791116700840&version=-1&method=2&fileName=%25E6%2596%25B0%25E5%25BB%25BA%25E7%25A9%25BA%25E7%2599%25BD%25E7%25AE%2580%25E6%258A%25A5.pptx&uuid=esY4FYGu
2021-04-22 09:24:44,574 - Logconfig.py - INFO - 下载文件被下载的文件夹
2021-04-22 09:24:55,600 - Logconfig.py - INFO - stop monitor
2021-04-22 09:24:57,782 - Logconfig.py - INFO - -----------------------------------test_TestDownload_02测试结束-------------------------------
2021-04-26 18:42:46,220 - Logconfig.py - INFO - --------------------------test_TestForm_01测试开始----------------------------------------
2021-04-26 18:42:49,870 - Logconfig.py - INFO - 以下为登录操作:18850009000@0U7TX93.yozocloud.cn,zsy123
2021-04-26 18:42:50,025 - Logconfig.py - INFO - start monitor!
2021-04-26 18:43:00,149 - Logconfig.py - INFO - 删除所有表单
2021-04-26 18:43:08,837 - Logconfig.py - INFO - 新建表单:问题是：你的名字
2021-04-26 18:43:13,087 - Logconfig.py - INFO - stop monitor
2021-04-26 18:43:15,263 - Logconfig.py - INFO - -----------------------------------test_TestForm_01测试结束-------------------------------
2021-04-26 18:43:15,273 - Logconfig.py - INFO - --------------------------test_TestForm_02测试开始----------------------------------------
2021-04-26 18:43:17,973 - Logconfig.py - INFO - start monitor!
2021-04-26 18:43:19,174 - Logconfig.py - INFO - 填写表单：答案是：周杰伦
2021-04-26 18:43:40,345 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='text']"}
  (Session info: chrome=90.0.4430.85)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='text']"}
  (Session info: chrome=90.0.4430.85)

2021-04-26 18:43:40,363 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 43, in element_input
    self.find_element(loc).send_keys(value)    # 再输入
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='text']"}
  (Session info: chrome=90.0.4430.85)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 43, in element_input
    self.find_element(loc).send_keys(value)    # 再输入
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='text']"}
  (Session info: chrome=90.0.4430.85)

2021-04-26 18:43:40,424 - Logconfig.py - INFO - stop monitor
2021-04-26 18:43:42,731 - Logconfig.py - INFO - -----------------------------------test_TestForm_02测试结束-------------------------------
2021-04-26 18:43:42,737 - Logconfig.py - INFO - --------------------------test_TestForm_03测试开始----------------------------------------
2021-04-26 18:43:45,059 - Logconfig.py - INFO - 以下为登录操作:18850009000@0U7TX93.yozocloud.cn,zsy123
2021-04-26 18:43:45,074 - Logconfig.py - INFO - start monitor!
2021-04-26 18:43:54,288 - Logconfig.py - INFO - 填写表单：答案是：周杰伦
2021-04-26 18:44:16,996 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='周杰伦']"}
  (Session info: chrome=90.0.4430.85)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='周杰伦']"}
  (Session info: chrome=90.0.4430.85)

2021-04-26 18:44:17,012 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 97, in verify_element_exist
    self.find_element(loc)
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='周杰伦']"}
  (Session info: chrome=90.0.4430.85)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 97, in verify_element_exist
    self.find_element(loc)
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='周杰伦']"}
  (Session info: chrome=90.0.4430.85)

2021-04-26 18:44:17,054 - Logconfig.py - INFO - stop monitor
2021-04-26 18:44:19,413 - Logconfig.py - INFO - -----------------------------------test_TestForm_03测试结束-------------------------------
2021-04-30 09:13:38,152 - Logconfig.py - INFO - --------------------------test_TestCalendar_01测试开始----------------------------------------
2021-04-30 09:13:40,858 - Logconfig.py - INFO - 以下为登录操作:18850009000@0U7TX93.yozocloud.cn,zsy123
2021-04-30 09:13:41,014 - Logconfig.py - INFO - start monitor!
2021-04-30 09:13:53,759 - Logconfig.py - INFO - 清空日程:新建的日程
2021-04-30 09:14:15,858 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

2021-04-30 09:14:15,892 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

2021-04-30 09:14:20,895 - Logconfig.py - INFO - 新建日程:新建的日程
2021-04-30 09:14:41,948 - Logconfig.py - INFO - stop monitor
2021-04-30 09:14:44,341 - Logconfig.py - INFO - -----------------------------------test_TestCalendar_01测试结束-------------------------------
2021-04-30 09:18:10,655 - Logconfig.py - INFO - --------------------------test_TestCalendar_01测试开始----------------------------------------
2021-04-30 09:18:13,450 - Logconfig.py - INFO - 以下为登录操作:18850009000@0U7TX93.yozocloud.cn,zsy123
2021-04-30 09:18:13,483 - Logconfig.py - INFO - start monitor!
2021-04-30 09:18:26,095 - Logconfig.py - INFO - 清空日程:新建的日程
2021-04-30 09:18:48,203 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

2021-04-30 09:18:48,209 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

2021-04-30 09:18:53,279 - Logconfig.py - INFO - 新建日程:新建的日程
2021-04-30 09:18:59,021 - Logconfig.py - INFO - 取消日程:新建的日程
2021-04-30 09:19:06,427 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span class="tui-full-calendar-weekday-schedule-title" data-title="..." title="新建的日程">新建的日程</span> is not clickable at point (1627, 711). Other element would receive the click: <div tabindex="-1" class="ant-modal-wrap" role="dialog" style="z-index: 3100;">...</div>
  (Session info: chrome=90.0.4430.93)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span class="tui-full-calendar-weekday-schedule-title" data-title="..." title="新建的日程">新建的日程</span> is not clickable at point (1627, 711). Other element would receive the click: <div tabindex="-1" class="ant-modal-wrap" role="dialog" style="z-index: 3100;">...</div>
  (Session info: chrome=90.0.4430.93)

2021-04-30 09:19:06,489 - Logconfig.py - INFO - stop monitor
2021-04-30 09:19:08,859 - Logconfig.py - INFO - -----------------------------------test_TestCalendar_01测试结束-------------------------------
2021-04-30 09:19:42,985 - Logconfig.py - INFO - --------------------------test_TestCalendar_01测试开始----------------------------------------
2021-04-30 09:19:45,399 - Logconfig.py - INFO - 以下为登录操作:18850009000@0U7TX93.yozocloud.cn,zsy123
2021-04-30 09:19:45,422 - Logconfig.py - INFO - start monitor!
2021-04-30 09:19:54,697 - Logconfig.py - INFO - 清空日程:新建的日程
2021-04-30 09:19:56,816 - Logconfig.py - INFO - 取消日程:新建的日程
2021-04-30 09:20:01,109 - Logconfig.py - INFO - 清空日程:新建的日程
2021-04-30 09:20:23,197 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

2021-04-30 09:20:23,198 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

2021-04-30 09:20:28,240 - Logconfig.py - INFO - 新建日程:新建的日程
2021-04-30 09:20:34,197 - Logconfig.py - INFO - 取消日程:新建的日程
2021-04-30 09:20:40,443 - Logconfig.py - INFO - 删除日程:新建的日程
2021-04-30 09:21:07,793 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(text(),"新建的日程")]"}
  (Session info: chrome=90.0.4430.93)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(text(),"新建的日程")]"}
  (Session info: chrome=90.0.4430.93)

2021-04-30 09:21:07,870 - Logconfig.py - INFO - stop monitor
2021-04-30 09:21:09,981 - Logconfig.py - INFO - -----------------------------------test_TestCalendar_01测试结束-------------------------------
2021-04-30 09:45:02,556 - Logconfig.py - INFO - --------------------------test_TestCalendar_01测试开始----------------------------------------
2021-04-30 09:45:05,127 - Logconfig.py - INFO - 以下为登录操作:18850009000@0U7TX93.yozocloud.cn,zsy123
2021-04-30 09:45:05,158 - Logconfig.py - INFO - start monitor!
2021-04-30 09:45:16,913 - Logconfig.py - INFO - 清空日程:新建的日程
2021-04-30 09:45:39,019 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

2021-04-30 09:45:39,019 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=90.0.4430.93)

2021-04-30 09:45:44,037 - Logconfig.py - INFO - 新建日程:新建的日程
2021-04-30 09:45:49,464 - Logconfig.py - INFO - 取消日程:新建的日程
2021-04-30 09:45:55,766 - Logconfig.py - INFO - 删除日程:新建的日程
2021-04-30 09:46:23,018 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(text(),"新建的日程")]"}
  (Session info: chrome=90.0.4430.93)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(text(),"新建的日程")]"}
  (Session info: chrome=90.0.4430.93)

2021-04-30 09:46:23,054 - Logconfig.py - INFO - stop monitor
2021-04-30 09:46:25,208 - Logconfig.py - INFO - -----------------------------------test_TestCalendar_01测试结束-------------------------------
2021-04-30 10:30:26,785 - Logconfig.py - INFO - --------------------------test_TestMember_04测试开始----------------------------------------
2021-04-30 10:30:31,177 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-04-30 10:30:31,395 - Logconfig.py - INFO - start monitor!
2021-04-30 10:30:44,436 - Logconfig.py - INFO - 以下为进入企业控制台
2021-04-30 10:30:49,941 - Logconfig.py - INFO - 进入部门:测试部
2021-04-30 10:30:52,059 - Logconfig.py - INFO - 删除成员:落荧
2021-04-30 10:30:56,374 - Logconfig.py - INFO - 进入部门:永中软件
2021-04-30 10:30:57,450 - Logconfig.py - INFO - 删除部门:测试部
2021-04-30 10:31:05,233 - Logconfig.py - INFO - 上传文件:yozo_import.xlsx
2021-04-30 10:31:13,797 - Logconfig.py - INFO - 获取随机密码
2021-04-30 10:31:41,434 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()="测试部"]"}
  (Session info: chrome=88.0.4324.182)

Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()="测试部"]"}
  (Session info: chrome=88.0.4324.182)

2021-04-30 10:31:41,435 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 97, in verify_element_exist
    self.find_element(loc)
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()="测试部"]"}
  (Session info: chrome=88.0.4324.182)

Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 97, in verify_element_exist
    self.find_element(loc)
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()="测试部"]"}
  (Session info: chrome=88.0.4324.182)

2021-04-30 10:31:41,438 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 119, in verify_file_exist
    self.verify_element_exist('//span[text()="%s"]' % filename)
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 97, in verify_element_exist
    self.find_element(loc)
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()="测试部"]"}
  (Session info: chrome=88.0.4324.182)

Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 119, in verify_file_exist
    self.verify_element_exist('//span[text()="%s"]' % filename)
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 97, in verify_element_exist
    self.find_element(loc)
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()="测试部"]"}
  (Session info: chrome=88.0.4324.182)

2021-04-30 10:31:41,484 - Logconfig.py - INFO - stop monitor
2021-04-30 10:31:43,983 - Logconfig.py - INFO - -----------------------------------test_TestMember_04测试结束-------------------------------
2021-04-30 10:33:50,816 - Logconfig.py - INFO - --------------------------test_TestMember_04测试开始----------------------------------------
2021-04-30 10:33:54,531 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-04-30 10:33:54,548 - Logconfig.py - INFO - start monitor!
2021-04-30 10:34:06,420 - Logconfig.py - INFO - 以下为进入企业控制台
2021-04-30 10:34:12,022 - Logconfig.py - INFO - 进入部门:测试部
2021-04-30 10:34:14,112 - Logconfig.py - INFO - 删除成员:落荧
2021-04-30 10:34:18,387 - Logconfig.py - INFO - 进入部门:永中软件
2021-04-30 10:34:19,499 - Logconfig.py - INFO - 删除部门:测试部
2021-04-30 10:34:27,128 - Logconfig.py - INFO - 上传文件:yozo_import.xlsx
2021-04-30 10:34:35,613 - Logconfig.py - INFO - 获取随机密码
2021-04-30 10:34:43,397 - Logconfig.py - INFO - 以下为退出登录操作
2021-04-30 10:34:44,999 - Logconfig.py - INFO - 以下为登录操作:13943225354,4c471d
2021-04-30 10:34:49,599 - Logconfig.py - INFO - 以下为进入优云指导
2021-04-30 10:35:12,156 - Logconfig.py - INFO - stop monitor
2021-04-30 10:35:14,376 - Logconfig.py - INFO - -----------------------------------test_TestMember_04测试结束-------------------------------
2021-04-30 10:38:19,309 - Logconfig.py - INFO - --------------------------test_TestCalendar_01测试开始----------------------------------------
2021-04-30 10:38:22,918 - Logconfig.py - INFO - 以下为登录操作:18850009000@0U7TX93.yozocloud.cn,zsy123
2021-04-30 10:38:22,936 - Logconfig.py - INFO - start monitor!
2021-04-30 10:38:36,403 - Logconfig.py - INFO - 清空日程:新建的日程
2021-04-30 10:38:58,432 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=88.0.4324.182)

Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=88.0.4324.182)

2021-04-30 10:38:58,432 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=88.0.4324.182)

Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的日程']"}
  (Session info: chrome=88.0.4324.182)

2021-04-30 10:39:03,481 - Logconfig.py - INFO - 新建日程:新建的日程
2021-04-30 10:39:09,069 - Logconfig.py - INFO - 取消日程:新建的日程
2021-04-30 10:39:15,355 - Logconfig.py - INFO - 删除日程:新建的日程
2021-04-30 10:39:42,532 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(text(),"新建的日程")]"}
  (Session info: chrome=88.0.4324.182)

Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(text(),"新建的日程")]"}
  (Session info: chrome=88.0.4324.182)

2021-04-30 10:39:42,538 - Logconfig.py - INFO - stop monitor
2021-04-30 10:39:44,694 - Logconfig.py - INFO - -----------------------------------test_TestCalendar_01测试结束-------------------------------
2021-05-10 17:17:21,193 - Logconfig.py - INFO - --------------------------test_TestMember_04测试开始----------------------------------------
2021-05-10 17:17:25,229 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-05-10 17:17:25,419 - Logconfig.py - INFO - start monitor!
2021-05-10 17:17:33,797 - Logconfig.py - INFO - 以下为进入企业控制台
2021-05-10 17:17:39,484 - Logconfig.py - INFO - 进入部门:测试部
2021-05-10 17:17:41,619 - Logconfig.py - INFO - 删除成员:落荧
2021-05-10 17:17:45,964 - Logconfig.py - INFO - 进入部门:永中软件
2021-05-10 17:17:47,028 - Logconfig.py - INFO - 删除部门:测试部
2021-05-10 17:17:54,666 - Logconfig.py - INFO - 上传文件:yozo_import.xlsx
2021-05-10 17:18:03,776 - Logconfig.py - INFO - 获取随机密码
2021-05-10 17:18:11,625 - Logconfig.py - INFO - 以下为退出登录操作
2021-05-10 17:18:13,216 - Logconfig.py - INFO - 以下为登录操作:13943225354,ff3fa8
2021-05-10 17:18:18,003 - Logconfig.py - INFO - 以下为进入优云指导
2021-05-10 17:18:31,223 - Logconfig.py - INFO - stop monitor
2021-05-10 17:18:33,342 - Logconfig.py - INFO - -----------------------------------test_TestMember_04测试结束-------------------------------
2021-05-17 13:18:26,565 - Logconfig.py - INFO - --------------------------test_TestMember_04测试开始----------------------------------------
2021-05-17 13:18:57,693 - Logconfig.py - INFO - --------------------------test_TestMember_04测试开始----------------------------------------
2021-05-17 13:25:29,066 - Logconfig.py - INFO - --------------------------test_TestMember_04测试开始----------------------------------------
2021-05-17 13:27:56,082 - Logconfig.py - INFO - --------------------------test_TestMember_04测试开始----------------------------------------
2021-05-17 13:27:59,252 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-05-17 13:27:59,485 - Logconfig.py - INFO - start monitor!
2021-05-17 13:28:07,763 - Logconfig.py - INFO - 以下为进入企业控制台
2021-05-17 13:28:13,347 - Logconfig.py - INFO - 进入部门:测试部
2021-05-17 13:28:15,494 - Logconfig.py - INFO - 删除成员:落荧
2021-05-17 13:28:19,767 - Logconfig.py - INFO - 进入部门:永中软件
2021-05-17 13:28:20,899 - Logconfig.py - INFO - 删除部门:测试部
2021-05-17 13:28:28,556 - Logconfig.py - INFO - 上传文件:yozo_import.xlsx
2021-05-17 13:28:37,151 - Logconfig.py - INFO - 获取随机密码
2021-05-17 13:28:44,911 - Logconfig.py - INFO - 以下为退出登录操作
2021-05-17 13:29:05,721 - Logconfig.py - INFO - 以下为登录操作:13943225354,c7ac5b
2021-05-17 13:29:10,403 - Logconfig.py - INFO - 以下为进入优云指导
2021-05-17 13:29:24,335 - Logconfig.py - INFO - stop monitor
2021-05-17 13:29:26,469 - Logconfig.py - INFO - -----------------------------------test_TestMember_04测试结束-------------------------------
2021-05-17 13:57:33,263 - Logconfig.py - INFO - --------------------------test_TestMember_03测试开始----------------------------------------
2021-05-17 13:57:36,549 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-05-17 13:57:36,567 - Logconfig.py - INFO - start monitor!
2021-05-17 13:57:47,176 - Logconfig.py - INFO - 以下为进入企业控制台
2021-05-17 13:57:52,796 - Logconfig.py - INFO - 进入部门:自动化部门
2021-05-17 13:57:54,882 - Logconfig.py - INFO - 删除成员:自动化1号
2021-05-17 13:58:14,934 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='自动化1号']/../..//input[@type='checkbox']"}
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='自动化1号']/../..//input[@type='checkbox']"}
  (Session info: chrome=90.0.4430.212)

2021-05-17 13:58:14,935 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='自动化1号']/../..//input[@type='checkbox']"}
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\shish\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shish\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='自动化1号']/../..//input[@type='checkbox']"}
  (Session info: chrome=90.0.4430.212)

2021-05-17 13:58:17,113 - Logconfig.py - INFO - 添加成员
2021-05-17 13:58:32,274 - Logconfig.py - INFO - 删除成员:自动化1号
2021-05-17 13:58:34,595 - Logconfig.py - INFO - 以下为退出登录操作
2021-05-17 13:58:36,321 - Logconfig.py - INFO - 以下为登录操作:18870102020,psd123
2021-05-17 13:58:39,910 - Logconfig.py - INFO - stop monitor
2021-05-17 13:58:42,023 - Logconfig.py - INFO - -----------------------------------test_TestMember_03测试结束-------------------------------
2021-05-17 13:59:22,147 - Logconfig.py - INFO - --------------------------test_TestMember_03测试开始----------------------------------------
2021-05-17 13:59:27,611 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-05-17 13:59:27,630 - Logconfig.py - INFO - start monitor!
2021-05-17 14:00:03,066 - Logconfig.py - INFO - --------------------------test_TestMember_04测试开始----------------------------------------
2021-05-17 14:00:06,879 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-05-17 14:00:06,897 - Logconfig.py - INFO - start monitor!
2021-05-25 10:06:39,132 - Logconfig.py - INFO - --------------------------test_TestApproval_00测试开始----------------------------------------
2021-05-25 10:06:45,501 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-05-25 10:06:45,724 - Logconfig.py - INFO - start monitor!
2021-05-25 10:07:11,039 - Logconfig.py - INFO - 清空所有审阅中数据
2021-05-25 10:07:37,061 - Logconfig.py - INFO - 以下为退出登录操作
2021-05-25 10:07:39,076 - Logconfig.py - INFO - 以下为登录操作:18870008000@0U7TX93.yozocloud.cn,zsy123
2021-05-25 10:07:45,553 - Logconfig.py - INFO - 新建文件夹:清空专用
2021-05-25 10:07:48,849 - Logconfig.py - INFO - 新建文件夹:清空专用
2021-05-25 10:07:52,077 - Logconfig.py - INFO - 删除所有文件
2021-05-25 10:08:02,769 - Logconfig.py - INFO - stop monitor
2021-05-25 10:08:04,880 - Logconfig.py - INFO - -----------------------------------test_TestApproval_00测试结束-------------------------------
2021-07-12 15:26:31,932 - Logconfig.py - INFO - --------------------------test_TestMember_04测试开始----------------------------------------
2021-07-12 15:26:37,053 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-07-12 15:26:37,086 - Logconfig.py - INFO - start monitor!
2021-07-12 15:26:45,818 - Logconfig.py - INFO - 以下为进入企业控制台
2021-07-12 15:26:52,621 - Logconfig.py - INFO - 进入部门:测试部
2021-07-12 15:26:54,903 - Logconfig.py - INFO - 删除成员:落荧
2021-07-12 15:26:59,247 - Logconfig.py - INFO - 进入部门:永中软件
2021-07-12 15:27:00,399 - Logconfig.py - INFO - 删除部门:测试部
2021-07-12 15:27:08,045 - Logconfig.py - INFO - 上传文件:yozo_import.xlsx
2021-07-12 15:27:16,851 - Logconfig.py - INFO - 获取随机密码
2021-07-12 15:27:24,933 - Logconfig.py - INFO - 以下为退出登录操作
2021-07-12 15:27:27,453 - Logconfig.py - INFO - 以下为登录操作:13943225354,b54ee9
2021-07-12 15:27:32,182 - Logconfig.py - INFO - 以下为进入优云指导
2021-07-12 15:27:47,593 - Logconfig.py - INFO - stop monitor
2021-07-12 15:27:50,127 - Logconfig.py - INFO - -----------------------------------test_TestMember_04测试结束-------------------------------
2021-07-13 14:51:06,305 - Logconfig.py - INFO - --------------------------test_TestMember_01测试开始----------------------------------------
2021-07-13 14:51:10,915 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-07-13 14:51:11,081 - Logconfig.py - INFO - start monitor!
2021-07-13 14:51:21,495 - Logconfig.py - INFO - 以下为进入企业控制台
2021-07-13 14:51:27,479 - Logconfig.py - INFO - 进入部门:自动化部门
2021-07-13 14:51:29,677 - Logconfig.py - INFO - 删除成员:自动化1号
2021-07-13 14:51:49,748 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='自动化1号']/../..//input[@type='checkbox']"}
  (Session info: chrome=91.0.4472.124)

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='自动化1号']/../..//input[@type='checkbox']"}
  (Session info: chrome=91.0.4472.124)

2021-07-13 14:51:49,749 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='自动化1号']/../..//input[@type='checkbox']"}
  (Session info: chrome=91.0.4472.124)

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='自动化1号']/../..//input[@type='checkbox']"}
  (Session info: chrome=91.0.4472.124)

2021-07-13 14:51:51,930 - Logconfig.py - INFO - 添加成员
2021-07-13 14:52:05,797 - Logconfig.py - INFO - 以下为退出登录操作
2021-07-13 14:52:08,258 - Logconfig.py - INFO - 以下为登录操作:18870102020,psd123
2021-07-13 14:52:13,103 - Logconfig.py - INFO - 以下为进入优云指导
2021-07-13 14:52:29,080 - Logconfig.py - INFO - stop monitor
2021-07-13 14:52:31,421 - Logconfig.py - INFO - -----------------------------------test_TestMember_01测试结束-------------------------------
2021-07-13 14:53:57,123 - Logconfig.py - INFO - --------------------------test_TestMember_01测试开始----------------------------------------
2021-07-13 14:54:01,173 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-07-13 14:54:01,191 - Logconfig.py - INFO - start monitor!
2021-07-13 14:54:08,346 - Logconfig.py - INFO - 以下为进入企业控制台
2021-07-13 14:54:14,460 - Logconfig.py - INFO - 进入部门:自动化部门
2021-07-13 14:54:16,680 - Logconfig.py - INFO - 删除成员:自动化1号
2021-07-13 14:54:21,347 - Logconfig.py - INFO - 添加成员
2021-07-13 14:54:35,622 - Logconfig.py - INFO - 以下为退出登录操作
2021-07-13 14:54:38,169 - Logconfig.py - INFO - 以下为登录操作:18870102020,psd123
2021-07-13 14:54:43,059 - Logconfig.py - INFO - 以下为进入优云指导
2021-07-13 14:54:58,581 - Logconfig.py - INFO - stop monitor
2021-07-13 14:55:00,936 - Logconfig.py - INFO - -----------------------------------test_TestMember_01测试结束-------------------------------
2021-07-15 17:00:27,567 - Logconfig.py - INFO - --------------------------test_TestMember_01测试开始----------------------------------------
2021-07-15 17:00:31,828 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-07-15 17:00:32,299 - Logconfig.py - INFO - start monitor!
2021-07-15 17:00:41,360 - Logconfig.py - INFO - 以下为进入企业控制台
2021-07-15 17:01:05,301 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=91.0.4472.124)

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=91.0.4472.124)

2021-07-15 17:01:05,314 - Logconfig.py - INFO - stop monitor
2021-07-15 17:01:09,287 - Logconfig.py - INFO - -----------------------------------test_TestMember_01测试结束-------------------------------
2021-07-15 17:05:34,273 - Logconfig.py - INFO - --------------------------test_TestMember_01测试开始----------------------------------------
2021-07-15 17:05:39,886 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-07-15 17:05:39,906 - Logconfig.py - INFO - start monitor!
2021-07-15 17:05:47,631 - Logconfig.py - INFO - 以下为进入企业控制台
2021-07-15 17:05:52,668 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (76, 199). Other element would receive the click: <a href="/epadmin/department/orgStructure">...</a>
  (Session info: chrome=91.0.4472.124)

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (76, 199). Other element would receive the click: <a href="/epadmin/department/orgStructure">...</a>
  (Session info: chrome=91.0.4472.124)

2021-07-15 17:05:52,690 - Logconfig.py - INFO - stop monitor
2021-07-15 17:05:55,265 - Logconfig.py - INFO - -----------------------------------test_TestMember_01测试结束-------------------------------
2021-07-15 17:13:44,241 - Logconfig.py - INFO - --------------------------test_TestMember_01测试开始----------------------------------------
2021-07-15 17:13:48,290 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-07-15 17:13:48,321 - Logconfig.py - INFO - start monitor!
2021-07-15 17:13:55,639 - Logconfig.py - INFO - 以下为进入企业控制台
2021-07-15 17:13:59,527 - Logconfig.py - INFO - stop monitor
2021-07-15 17:14:02,098 - Logconfig.py - INFO - -----------------------------------test_TestMember_01测试结束-------------------------------
2021-07-15 17:15:30,723 - Logconfig.py - INFO - --------------------------test_TestMember_04测试开始----------------------------------------
2021-07-15 17:15:34,654 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-07-15 17:15:34,672 - Logconfig.py - INFO - start monitor!
2021-07-15 17:15:41,783 - Logconfig.py - INFO - 以下为进入企业控制台
2021-07-15 17:15:48,244 - Logconfig.py - INFO - 进入部门:测试部
2021-07-15 17:15:50,421 - Logconfig.py - INFO - 删除成员:落荧
2021-07-15 17:15:54,845 - Logconfig.py - INFO - 进入部门:永中软件
2021-07-15 17:15:55,990 - Logconfig.py - INFO - 删除部门:测试部
2021-07-15 17:16:03,832 - Logconfig.py - INFO - 上传文件:yozo_import.xlsx
2021-07-15 17:16:12,392 - Logconfig.py - INFO - 获取随机密码
2021-07-15 17:16:20,512 - Logconfig.py - INFO - 以下为退出登录操作
2021-07-15 17:16:22,872 - Logconfig.py - INFO - 以下为登录操作:13943225354,383f8b
2021-07-15 17:16:27,825 - Logconfig.py - INFO - 以下为进入优云指导
2021-07-15 17:17:01,035 - Logconfig.py - INFO - stop monitor
2021-07-15 17:17:03,772 - Logconfig.py - INFO - -----------------------------------test_TestMember_04测试结束-------------------------------
2021-07-15 17:18:02,419 - Logconfig.py - INFO - --------------------------test_TestMember_01测试开始----------------------------------------
2021-07-15 17:18:06,606 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-07-15 17:18:06,623 - Logconfig.py - INFO - start monitor!
2021-07-15 17:18:14,385 - Logconfig.py - INFO - 以下为进入企业控制台
2021-07-15 17:18:20,414 - Logconfig.py - INFO - 进入部门:自动化部门
2021-07-15 17:18:22,683 - Logconfig.py - INFO - 删除成员:自动化1号
2021-07-15 17:18:27,348 - Logconfig.py - INFO - 添加成员
2021-07-15 17:18:41,513 - Logconfig.py - INFO - 以下为退出登录操作
2021-07-15 17:18:44,188 - Logconfig.py - INFO - 以下为登录操作:18870102020,psd123
2021-07-15 17:18:49,135 - Logconfig.py - INFO - 以下为进入优云指导
2021-07-21 15:09:59,943 - Logconfig.py - INFO - --------------------------test_TestApproval_01测试开始----------------------------------------
2021-07-21 15:10:04,985 - Logconfig.py - INFO - 以下为登录操作:18870008000@0U7TX93.yozocloud.cn,zsy123
2021-07-21 15:10:05,217 - Logconfig.py - INFO - start monitor!
2021-08-04 14:37:45,676 - Logconfig.py - INFO - --------------------------test_TestApproval_00测试开始----------------------------------------
2021-08-04 14:37:50,678 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-08-04 14:37:50,893 - Logconfig.py - INFO - start monitor!
2021-08-04 14:37:59,060 - Logconfig.py - INFO - 清空所有审阅中数据
2021-08-12 11:02:02,135 - Logconfig.py - INFO - --------------------------test_TestApproval_00测试开始----------------------------------------
2021-08-12 11:02:06,002 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-08-12 11:02:06,239 - Logconfig.py - INFO - start monitor!
2021-08-12 11:02:13,106 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=91.0.4472.124)

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=91.0.4472.124)

2021-08-12 11:02:13,127 - Logconfig.py - INFO - stop monitor
2021-08-12 11:02:16,148 - Logconfig.py - INFO - -----------------------------------test_TestApproval_00测试结束-------------------------------
2021-08-12 11:08:21,791 - Logconfig.py - INFO - --------------------------test_TestApproval_00测试开始----------------------------------------
2021-08-12 11:08:26,181 - Logconfig.py - INFO - 以下为登录操作:18810002000@0U7TX93.yozocloud.cn,zsy123
2021-08-12 11:08:26,196 - Logconfig.py - INFO - start monitor!
2021-08-12 11:08:33,721 - Logconfig.py - INFO - 清空所有审阅中数据
2021-08-12 11:08:37,217 - Logconfig.py - INFO - 进行的审阅操作是：通过
2021-08-12 11:08:57,288 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='同意']"}
  (Session info: chrome=91.0.4472.124)

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='同意']"}
  (Session info: chrome=91.0.4472.124)

2021-08-12 11:08:57,289 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='同意']"}
  (Session info: chrome=91.0.4472.124)

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\Administrator\PycharmProjects\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='同意']"}
  (Session info: chrome=91.0.4472.124)

2021-08-12 11:09:01,314 - Logconfig.py - INFO - 以下为退出登录操作
2021-08-12 11:09:03,667 - Logconfig.py - INFO - 以下为登录操作:18870008000@0U7TX93.yozocloud.cn,zsy123
2021-08-12 11:09:10,306 - Logconfig.py - INFO - 新建文件夹:清空专用
2021-08-12 11:09:13,870 - Logconfig.py - INFO - 新建文件夹:清空专用
2021-08-12 11:09:17,211 - Logconfig.py - INFO - 删除所有文件
2021-08-12 11:09:27,852 - Logconfig.py - INFO - stop monitor
2021-08-12 11:09:30,249 - Logconfig.py - INFO - -----------------------------------test_TestApproval_00测试结束-------------------------------
