2021-05-19 18:51:36,159 - Logconfig.py - INFO - --------------------------test_TestTodo_01测试开始----------------------------------------
2021-05-19 18:51:40,800 - Logconfig.py - INFO - 以下为登录操作:18850009000@0U7TX93.yozocloud.cn,zsy123
2021-05-19 18:51:41,086 - Logconfig.py - INFO - start monitor!
2021-05-19 18:51:49,275 - Logconfig.py - INFO - 清空日程:新建的待办
2021-05-19 18:52:11,313 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:52:11,315 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:52:16,363 - Logconfig.py - INFO - 新建待办:新建的待办
2021-05-19 18:52:20,039 - Logconfig.py - INFO - 删除待办:新建的待办
2021-05-19 18:52:23,174 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="title_6068ef hidden-line-1">...</div> is not clickable at point (1047, 109). Other element would receive the click: <div class="ant-drawer-mask"></div>
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="title_6068ef hidden-line-1">...</div> is not clickable at point (1047, 109). Other element would receive the click: <div class="ant-drawer-mask"></div>
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:52:23,204 - Logconfig.py - INFO - stop monitor
2021-05-19 18:52:25,514 - Logconfig.py - INFO - -----------------------------------test_TestTodo_01测试结束-------------------------------
2021-05-19 18:52:43,470 - Logconfig.py - INFO - --------------------------test_TestTodo_01测试开始----------------------------------------
2021-05-19 18:52:46,777 - Logconfig.py - INFO - 以下为登录操作:18850009000@0U7TX93.yozocloud.cn,zsy123
2021-05-19 18:52:46,802 - Logconfig.py - INFO - start monitor!
2021-05-19 18:52:55,375 - Logconfig.py - INFO - 清空日程:新建的待办
2021-05-19 18:52:57,485 - Logconfig.py - INFO - 删除待办:新建的待办
2021-05-19 18:53:00,605 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="title_6068ef hidden-line-1">...</div> is not clickable at point (1047, 109). Other element would receive the click: <div class="ant-drawer-mask"></div>
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="title_6068ef hidden-line-1">...</div> is not clickable at point (1047, 109). Other element would receive the click: <div class="ant-drawer-mask"></div>
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:53:00,606 - Logconfig.py - INFO - 清空日程:新建的待办
2021-05-19 18:53:03,655 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="title_6068ef hidden-line-1">...</div> is not clickable at point (1047, 109). Other element would receive the click: <div class="ant-drawer-mask"></div>
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="title_6068ef hidden-line-1">...</div> is not clickable at point (1047, 109). Other element would receive the click: <div class="ant-drawer-mask"></div>
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:53:08,659 - Logconfig.py - INFO - 新建待办:新建的待办
2021-05-19 18:53:09,745 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (127, 44). Other element would receive the click: <div class="ant-drawer-mask"></div>
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span>...</span> is not clickable at point (127, 44). Other element would receive the click: <div class="ant-drawer-mask"></div>
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:53:09,786 - Logconfig.py - INFO - stop monitor
2021-05-19 18:53:12,092 - Logconfig.py - INFO - -----------------------------------test_TestTodo_01测试结束-------------------------------
2021-05-19 18:55:01,047 - Logconfig.py - INFO - --------------------------test_TestTodo_01测试开始----------------------------------------
2021-05-19 18:55:04,706 - Logconfig.py - INFO - 以下为登录操作:18850009000@0U7TX93.yozocloud.cn,zsy123
2021-05-19 18:55:04,730 - Logconfig.py - INFO - start monitor!
2021-05-19 18:55:13,501 - Logconfig.py - INFO - 清空日程:新建的待办
2021-05-19 18:55:15,584 - Logconfig.py - INFO - 删除待办:新建的待办
2021-05-19 18:55:19,796 - Logconfig.py - INFO - 清空日程:新建的待办
2021-05-19 18:55:21,854 - Logconfig.py - INFO - 删除待办:新建的待办
2021-05-19 18:55:26,058 - Logconfig.py - INFO - 清空日程:新建的待办
2021-05-19 18:55:48,110 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:55:48,111 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:55:53,145 - Logconfig.py - INFO - 新建待办:新建的待办
2021-05-19 18:55:57,014 - Logconfig.py - INFO - 删除待办:新建的待办
2021-05-19 18:56:24,355 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(text(),"新建的待办")]"}
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(text(),"新建的待办")]"}
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:56:24,405 - Logconfig.py - INFO - stop monitor
2021-05-19 18:56:27,091 - Logconfig.py - INFO - -----------------------------------test_TestTodo_01测试结束-------------------------------
2021-05-19 18:56:57,602 - Logconfig.py - INFO - --------------------------test_TestTodo_01测试开始----------------------------------------
2021-05-19 18:57:01,163 - Logconfig.py - INFO - 以下为登录操作:18850009000@0U7TX93.yozocloud.cn,zsy123
2021-05-19 18:57:01,187 - Logconfig.py - INFO - start monitor!
2021-05-19 18:57:09,831 - Logconfig.py - INFO - 清空日程:新建的待办
2021-05-19 18:57:31,911 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:57:31,912 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 50, in element_click
    self.find_element(loc).click()
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='新建的待办']"}
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:57:36,957 - Logconfig.py - INFO - 新建待办:新建的待办
2021-05-19 18:57:41,074 - Logconfig.py - INFO - 删除待办:新建的待办
2021-05-19 18:58:08,438 - Logconfig.py - ERROR - Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(text(),"新建的待办")]"}
  (Session info: chrome=90.0.4430.212)

Traceback (most recent call last):
  File "D:\YZ_cloud\SaaS\Object\base.py", line 32, in find_element
    return self.driver.find_element_by_xpath(loc)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DZPC1911362\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(text(),"新建的待办")]"}
  (Session info: chrome=90.0.4430.212)

2021-05-19 18:58:08,448 - Logconfig.py - INFO - stop monitor
2021-05-19 18:58:11,018 - Logconfig.py - INFO - -----------------------------------test_TestTodo_01测试结束-------------------------------
